name: Sync YuQue Docs To Blog
on: [push]
jobs:
  # run sync script
  sync:
    runs-on: ubuntu-latest
    environment: SyncToken
    steps:
    - uses: actions/checkout@v3
    - uses: sergioramos/yarn-actions/install@v6
      with:
        frozen-lockfile: true

    - name: Syncing
      run: yarn sync --git -t ${{secrets.YQ_TOKEN}}

#    - name: Formatting
