name: Sync YuQue Docs To Blog
on:
  push:
    branchs:
      - main
jobs:
  # run sync script
  sync:
    runs-on: ubuntu-latest
    environment: SyncToken
    steps:
    - use: sergioramos/yarn-actions/install@v6
      with:
        frozen-lockfile: true

    - name: Install deps
      run: npm install

    - name: Syncing
      run: node ./.scripts/yuque-sync.js -git -t ${{secrets.YQ_TOKEN}}

#    - name: Formatting
