name: Sync YuQue Docs To Blog
on: [push]
jobs:
  # run sync script
  sync:
    runs-on: ubuntu-latest
    environment: SyncToken
    steps:
    - uses: sergioramos/yarn-actions/install@v6
      with:
        frozen-lockfile: true

    - name: Install deps
      run: cd .scripts & yarn install

    - name: Syncing
      run: node ./.scripts/sync/syncAction.js -git -t ${{secrets.YQ_TOKEN}}

#    - name: Formatting
